### ISSUE TITLE
Add screenshot?

### ISSUE THREAD

**Issue by AdamGreenhill** [GelaniNijraj/PyMaterial#11]
Is it possible for you to add a screenshot of what PyMaterial looks like?

**Comment by GelaniNijraj** [comment]
@IronManMark20 have added the screenshots of how it currently looks. Although the components are not completely working and they lack a significant material attribute, ripples. We'll update the screenshots as the work progresses. :smile:

**Comment by AdamGreenhill** [comment]
Thanks!
